---
- name: Deploy my-java-app container
  hosts: all
  become: yes
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: mydockergreens/my-java-app
        tag: latest
        source: pull

    - name: Run Docker container from the image
      docker_container:
        name: my-java-app
        image: mydockergreens/my-java-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "8070:8070"
        volumes:
          - /path/on/host:/path/in/container # Optional, for persistent data
