---
- name: Deploy Docker Container
  hosts: docker_agents
  become: true
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: mydockergreens/my-java-app
        tag: latest
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: java-container
        image: mydockergreens/my-java-app:latest
        state: started
        ports:
          - "8070:8070"  # Map host port 8080 to container port 80
